# Generated by Django 4.1 on 2022-08-31 23:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lembrete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='data',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
