# Generated by Django 4.1 on 2022-09-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lembrete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
