# Generated by Django 4.1.10 on 2023-10-28 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_cod_doador_agendamento_cod_doador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cod_doador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.doador'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
