# Generated by Django 4.1.10 on 2023-10-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_dispersao_qtd_bolsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='dia_disponivel',
        ),
    ]
