# Generated by Django 4.1.10 on 2023-12-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_agendamento_dia_disponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VW_HistoricoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'vw_historicoDoacao',
                'managed': False,
            },
        ),
    ]
