# Generated by Django 4.1.10 on 2023-12-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vw_historicodoacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='vw_agendaFuturo',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'vw_agendaFuturo',
                'managed': False,
            },
        ),
    ]
